# Generated by Django 3.0.4 on 2020-04-29 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200429_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDImage_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Product Image 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDImage_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Product Image 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDImage_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Product Image 4'),
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNAlternative', models.ManyToManyField(related_name='alternative_products', to='product.Product', verbose_name='Product_Alternative')),
                ('PALNProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product_Alternative',
                'verbose_name_plural': 'Product_Alternative',
            },
        ),
    ]
