# Generated by Django 3.0.4 on 2020-04-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200429_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_alternative',
            options={'verbose_name': 'Product_Alternative', 'verbose_name_plural': 'Product Alternative'},
        ),
        migrations.CreateModel(
            name='Product_Accessoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAlternative', models.ManyToManyField(related_name='product_accessoris', to='product.Product', verbose_name='Product Accessoris')),
                ('PACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessoris_product', to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product_Accessoris',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
