# Generated by Django 3.0.4 on 2020-04-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200429_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='PRDCategory',
        ),
    ]
