# Generated by Django 3.0.4 on 2020-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDName', models.CharField(max_length=50, verbose_name='Name')),
                ('BRDDesc', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARName', models.CharField(max_length=50, verbose_name='Name')),
                ('VARDesc', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variant',
            },
        ),
    ]
