# Generated by Django 3.0.4 on 2020-04-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRDDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
